### ISSUE TITLE
question sur getDepartmentName

### ISSUE THREAD

**Issue by D4llo** [cedricr/100joursdezbeul#10]
Salut,

Je me demandais quel était l'usage du `throw` ici ?

https://github.com/cedricr/100joursdezbeul/blob/a02e217a422d16771066b6f5add5dd7daf674555/src/lib/utils.ts#L37

Le code teste deux fois pour voir si `dept` est falsy. Une fois avant de throw et une fois dans le ternaire.

```typescript
export function getDepartmentName(code: string): string {
	const dept = DEPARTMENTS.find((elt) => elt.code === code);
	if (!dept) {
		throw new Error(`le département ${code} est inconnu`);
	}
	return dept ? dept.nom : '(inconnu)';
}
```

Est-ce qu'on peut retirer le if/throw et retourner directement le ternaire ?

```typescript
export function getDepartmentName(code: string): string {
	const dept = DEPARTMENTS.find((elt) => elt.code === code);
	return dept ? dept.nom : '(inconnu)';
}
```

Qu'en pensez-vous?

**Comment by cedricr** [comment]
Oui complètement, le code peut être amélioré!
L'avantage du throw serait (mais à retester) que le site ne sera pas généré en cas d'erreur dans le data, ce qui me parait mieux que d'avoir une ligne "inconnu" qu'on devrait de toute façon corriger par la suite.
Par contre après le throw, pas besoin de retester `dept` bien sûr.

**Comment by cedricr** [comment]
Réglé par https://github.com/cedricr/100joursdezbeul/pull/91
