### ISSUE TITLE
Hierarchie du classement + Effet Hover

### ISSUE THREAD

**Issue by SvenLochner** [cedricr/100joursdezbeul#104]
Salut,

J'ai quelques propositions UX/UI pour le classement

![zbeul leaderboard 2](https://user-images.githubusercontent.com/91607339/236844965-159e7f8f-f17f-4277-97d5-5ccb3da6ca9a.png)

1 - Rectification au niveau hiérarchique, inverser le placement du rang et du département permet d'avoir une meilleur visibilité du classement. C'est aussi un "standard" pour la plupart des classements, la plupart des utilisateurs sont habitués à voir un classement dans cet ordre.

2 - Position dans le classement. Je pense que ca pourrait être une bonne idée d'ajouter un élément visuel aux changements dans le classement, ca rajoute un peu de dynamisme et ça rend le classement plus vivant. 

3 - Effet hover. Ca serait une bonne idée de rajouter un effet hover sur le container, on pourrait même l'adapter pour les trois premiers afin de donner plus de vie au classement, voir example ci dessous:

![Zbeul Animation](https://user-images.githubusercontent.com/91607339/236846271-34e7b5e7-6119-4da0-b901-e0b533db8945.gif)

Faites moi savoir ce que vous en pensez :)

**Comment by D4llo** [comment]
1. Rang | Département | Points correspond à l'ancien ordre. De mémoire c'est #17 (pas de soucis perso pour revenir sur cet ordre. À discuter.)
2. duplicate de #70 
3. ok pour le hover

Sinon

* merci pour le retour !
* trop cool le gif !
* est-ce que tu veux dev le hover ?

**Comment by SvenLochner** [comment]
Salut @D4llo,

Merci pour le retour ! Désolé pour les doublons, je suis pas (encore) habitué de Github. Pour le point 1 et 2 je suppose que j’abandonne ce point et je poste mes idées dans les points correspondant ?

Mes capacités de devs sont très limités haha (doux euphémisme), si il y a pas d'autre choix je veux bien tenter mais si il existe une alternative je suis preneur. Je peux partager les assets nécessaire et/ou le ficher Figma si besoin.

**Comment by D4llo** [comment]
Aucun soucis pour les doublons. Merci de venir partager tes idées ! C'est le plus important :smiley: 

J'extrais le point 1 dans une nouvelle issue pour en parler plus facilement. Cela se passe ici #116

Le point 2 on peut en parler dans l'issue #70 

Le point 3 va continuer à être discuté ici.

Pour le dev, pas de soucis je propose mais c'est bien sûr ouvert à tout le monde. Si c'est validé, ce sera fait par qui le souhaite. Tout le monde est pas dev et bien heureusement sinon niveau interface ce serait vite limité :smile:

**Comment by D4llo** [comment]
Pour le hover plutôt rouge ou bleu ?

![red](https://github.com/cedricr/100joursdezbeul/assets/131776117/d5d1f691-6192-4181-8732-3406cab8df02)
![blue](https://github.com/cedricr/100joursdezbeul/assets/131776117/e4697606-f43d-4c33-b5c2-25365199f0bc)

**Comment by juliemoynat** [comment]
@D4llo j'aimais bien quand ça reprenait la couleur des médailles pour les 3 premiers et gris pour les autres 🤔

**Comment by D4llo** [comment]
@juliemoynat ah oui je n'avais pas vu ! Superbe idée. Je vais m'occuper de changer ça. Histoire d'avoir un peu de couleur je suis tenté de faire gold/silver/bronze et bleu plutôt que gris. Je trouve que ça accentue le côté "je suis un lien" aussi. Un avis là dessus ?

**Comment by D4llo** [comment]
Exemple de rendu (gif):

![colors](https://github.com/cedricr/100joursdezbeul/assets/131776117/5e8740b2-cfad-4088-a947-1d495b1b0ad2)

Ça me donne bien envie de colorier l’intérieur du chevron de la couleur de la bordure de gauche :)
