### ISSUE TITLE
Reconnaissance des actions impossibles à cause d'interdiction

### ISSUE THREAD

**Issue by D4llo** [cedricr/100joursdezbeul#108]
J'aimerai savoir ce que nous souhaitons faire des actions interdites par les autorités ?

[Déplacement de Macron : une loi antiterroriste de nouveau utilisée pour interdire une manifestation à Vendôme](https://www.liberation.fr/checknews/deplacement-de-macron-une-loi-anti-terroriste-de-nouveau-utilisee-pour-interdire-une-manifestation-a-vendome-un-refere-liberte-a-ete-depose-20230425_3F5Z5XKDWFCCNGYJ7TVTQGVLOA/)

Je propose de donner la moitié des points prévu, soit `(chahut + manif) * président / 2 <=> 2 * 6 / 2 <=> 6pts`.

```
export function enrichData(data: ActionEvent[]) {
	data.forEach((event) => {
		const score = event.actions.map((action) => ACTION_SCORE[action]).reduce((a, b) => a + b);
		const multiplier = event.cibles
			.map((target) => TARGET_MULTIPLIER[target])
			.reduce((a, b) => a + b);
		const forbidden = event.forbidden ? 2 : 1;
		event.score = score * multiplier / forbidden;
	});
	return data;
}
```
Edit: ce cas spéfique n'est plus d'actualité https://www.leparisien.fr/politique/macron-dans-le-loir-et-cher-des-associations-deposent-un-refere-liberte-contre-linterdiction-de-manifester-25-04-2023-CVOQWYZNI5FH3GU52CHXHPGQZY.php

**Comment by D4llo** [comment]
> C'est comme une annulation non ?

annulation -> action de la ou des personnalités n'a pas pu se faire ou se finir
interdiction -> action de la ou des personnalités a eu lieu mais le chahut n'a pas pu se faire (et nous n'invitons pas à ne pas respecter la loi)

**Comment by D4llo** [comment]
Exemple d'action qui pour moi mérite 3pts

![image](https://user-images.githubusercontent.com/131776117/236927138-5f36355d-05cd-4551-9c19-4bdc2952e030.png)

Cela nous donnerait `manif * président / 2 <=>1 * 6 / 2 <=> 3pts`

**Comment by cedricr** [comment]
On a maintenant la "débauche sécuritaire" qui recoupe en partie cet usage.
