### ISSUE TITLE
Supprimer l'unité en doublon avec le titre de la colonne

### ISSUE THREAD

**Issue by D4llo** [cedricr/100joursdezbeul#110]
![image](https://user-images.githubusercontent.com/131776117/236929010-b568c8eb-22f8-453b-bc52-d1020f105427.png)

En plus les raccourcis de ce genre c'est pas toujours évident

**Comment by cedricr** [comment]
@juliemoynat tu as un point de vue accessibilité là dessus?

**Comment by juliemoynat** [comment]
C'est OK car on a bien un en-tête de colonne bien rattaché.

**Comment by juliemoynat** [comment]
Au final, voir dans la PR #144 , on a essayé de supprimer le texte "pts" mais ça rendait illisible le tableau des scores donc on a plutôt fait une petite refonte graphique : mettre "pts" plus petit + ajouter un "e" en exposant pour le classement. Je me perdais toujours entre les 2 colonnes et là, c'est plus clair !
