### ISSUE TITLE
Casseroliser les médailles

### ISSUE THREAD

**Issue by D4llo** [cedricr/100joursdezbeul#113]
Je me suis dit que ça pourrait être drôle de donner un petit côté casserolle aux médailles... 

![Medaille d'or](https://github.com/cedricr/100joursdezbeul/assets/91607339/df45a2df-b997-4497-8519-45b03353847d)
![Médaille d'argent](https://github.com/cedricr/100joursdezbeul/assets/91607339/775dcb48-e287-46d7-abc2-cc98fbfb8e46)
![Médaille de Bronze](https://github.com/cedricr/100joursdezbeul/assets/91607339/31fe3673-a315-4be1-8fba-c77d4a06ae56)

Qu'en pensez-vous ?

<img width="942" alt="Classement médailles" src="https://github.com/cedricr/100joursdezbeul/assets/91607339/4dcd9d1a-bc51-460a-a3ec-3bda54263874">

_Originally posted by @SvenLochner in https://github.com/cedricr/100joursdezbeul/issues/17#issuecomment-1540060750_

**Comment by D4llo** [comment]
On abandonne l'aspect ruban mais le rendu est plus explicite. La noire fait plus "casserole" selon moi. Perso je préfère :)

**Comment by SvenLochner** [comment]
Yes ! Super bonne idée @CharligaUX. Je trouve que le noir rend la casserole plus visible aussi.

**Comment by CharligaUX** [comment]
Merci ! Je vous mets les SVG noires bien propre ici dans qq minutes. :)

**Comment by juliemoynat** [comment]
Ah casserole d'or, d'argent et de bronze, j'aime bien comme ça ! En noir aussi, c'est mieux !

**Comment by CharligaUX** [comment]
![Casserole_Noire_1](https://github.com/cedricr/100joursdezbeul/assets/133201336/26e669ac-fb5a-4e6b-82be-87cdfeb22639)
![Casserole_Noire_2](https://github.com/cedricr/100joursdezbeul/assets/133201336/b2b69a52-0d4d-4166-9e74-44729a242d0d)
![Casserole_Noire_3](https://github.com/cedricr/100joursdezbeul/assets/133201336/650e2a1a-34a5-462b-a542-5d5e5bc8c2e7)
