### ISSUE TITLE
Ajout points Rhône suite 8 mai

### ISSUE THREAD

**Issue by 1823049576** [cedricr/100joursdezbeul#114]
Bonjour,

Pouvez-vous revoir le nombre de points remportés par le Rhône suite à la venue sur Lyon de Macron, Ndiaye et Dupond-Moretti le 8 mai dernier svp ? Au niveau des facteurs ça donnerait x6, x3 et x3.

D'après la dépêche suivante, ils étaient bien présents tous les 3 : https://actu.fr/auvergne-rhone-alpes/lyon_69123/8-mai-emmanuel-macron-defend-a-lyon-une-republique-francaise-ni-bonne-ni-mauvaise_59506234.html
"A Lyon, Emmanuel Macron était accompagné du garde des Sceaux Eric Dupond-Moretti, du ministre de l’Education nationale Pap Ndiaye et de la secrétaire d’Etat chargée des Anciens combattants et de la Mémoire Patricia Miralles."

Proposition de calcul suite à divers échanges sur les réseaux :
- Chahut (manifestation, casserolade, huée…) : 1 pt + Annulation d’une visite 🎉 : 5 pts + Action créative : 2 pts => 8 pts
- Président de la République : x6 + Ministre x3 + Ministre x3 => x12
=> Total = 96 pts
(Pour éviter d'accumuler trop de points en multipliant par le facteur de chacune des personnalités : 8 pts x 6 x 3 x 3 = 432 pts -> pas vraiment fair-play 😉)

Merci pour votre réponse, et surtout pour cette belle invention #100joursdezbeul !! ✊

**Comment by D4llo** [comment]
Aujourd'hui l'algo c'est la somme des actions mulitplié par la somme des personnalités.

Par exemple pour l'[Herault](https://100joursdezbeul.fr/departement/34), on a `(1+3+2) * (6+3) == 54`

Dans ce cas, nous sommes sur le même compte de 8 pour la somme des actions. Voyons du côté des personnalité en ce basant sur le lien de actu.fr :

- Emmanuel Macron (président) x6
- Eric Dupond-Moretti (ministre) x3 
- Pap Ndiaye (ministre) x3 
- Patricia Miralles (secrétaire d’Etat) x1

Donc un multiplicateur de 6+3+3+1 soit 13 ! Cela nous donnerait un total de 8x13 donc 104 points

**Comment by D4llo** [comment]
Pas de soucis :)

Pour le calcul, je ne m'occupe pas du décompte des points et datas. Ce sera confirmé avec l'ensemble de l'équipe.

**Comment by D4llo** [comment]
Après moult discussion et revue de presse et argumentaire féroce d'un membre de Solidaire Informatique Lyon, nous sommes arrivés à la conclusion qu'il y a eu deux évènements ce jour là :

![image](https://github.com/cedricr/100joursdezbeul/assets/131776117/23dcce55-fb51-41b5-ba8f-937340587c5e)

Grâce à @cedricr [C'est déja en ligne !](https://100joursdezbeul.fr/date/2023-05-08)
