### ISSUE TITLE
Ajouter le lien vers le compte twitter dans le footer

### ISSUE THREAD

**Issue by CharligaUX** [cedricr/100joursdezbeul#118]

**Comment by D4llo** [comment]
On peut aussi ajouter le mastodon

**Comment by CharligaUX** [comment]
Très bien, cela pourrait être intégré sous cette forme dans un 1er temps (puis sous forme d'icon à étudier), dans le footer ; c'est-à-dire sur toutes les pages du site.

![100joursdezbeul fr_footer](https://github.com/cedricr/100joursdezbeul/assets/133201336/0a96b569-14ea-41d8-9167-9f8c8e938cc2)

J'ajoute une petit plus : mettre des espaces insécable entre les mots d'un même lien (ex : Mentions légales) pour éviter en fonction des résolutions que le lien ne soit scindé sur 2 lignes.

**Comment by D4llo** [comment]
Je trouve ça trop volumineux alors j'ai changé un peu (et retirer une partie des RS)

![image](https://github.com/cedricr/100joursdezbeul/assets/131776117/60a55df8-94aa-4f53-a6e1-37a69f2e8055)

```html

	<ul class="flex justify-center gap-1">
		<li>
			<svg
				xmlns="http://www.w3.org/2000/svg"
				viewBox="0 0 448 512"
				class="inline-block w-4"
				role="img"
				aria-labelledby="solidaires-informatique-mastodon-title"
				><!--! Font Awesome Pro 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
				<title id="solidaires-informatique-mastodon-title"
					>Le compte Mastodon de Solidaires Informatique</title
				><path
					d="M433 179.11c0-97.2-63.71-125.7-63.71-125.7-62.52-28.7-228.56-28.4-290.48 0 0 0-63.72 28.5-63.72 125.7 0 115.7-6.6 259.4 105.63 289.1 40.51 10.7 75.32 13 103.33 11.4 50.81-2.8 79.32-18.1 79.32-18.1l-1.7-36.9s-36.31 11.4-77.12 10.1c-40.41-1.4-83-4.4-89.63-54a102.54 102.54 0 0 1-.9-13.9c85.63 20.9 158.65 9.1 178.75 6.7 56.12-6.7 105-41.3 111.23-72.9 9.8-49.8 9-121.5 9-121.5zm-75.12 125.2h-46.63v-114.2c0-49.7-64-51.6-64 6.9v62.5h-46.33V197c0-58.5-64-56.6-64-6.9v114.2H90.19c0-122.1-5.2-147.9 18.41-175 25.9-28.9 79.82-30.8 103.83 6.1l11.6 19.5 11.6-19.5c24.11-37.1 78.12-34.8 103.83-6.1 23.71 27.3 18.4 53 18.4 175z"
				/></svg
			>
			<a href="https://syndicat.solidaires.org/@SolInfoNat" rel="me"
				>@SolInfoNat@syndicat.solidaires.org</a
			><span aria-hidden="true">&nbsp;· </span>
		</li>
		<li>
			<svg
				xmlns="http://www.w3.org/2000/svg"
				viewBox="0 0 512 512"
				class="inline-block w-4"
				role="img"
				aria-labelledby="solidaires-informatique-twitter-title"
				><!--! Font Awesome Pro 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><title
					id="solidaires-informatique-twitter-title"
					>Le compte Twitter de Solidaires Informatique</title
				><path
					d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"
				/></svg
			><a href="https://twitter.com/SolInfoNat">@SolInfoNat</a>
		</li>
	</ul>
```

**Comment by CharligaUX** [comment]
A mettre en taille 40px,... avec 15px entre chaque (si ça te va)

![YouTube_Negative](https://github.com/cedricr/100joursdezbeul/assets/133201336/1e719360-c33b-4890-9246-492400f8f4de)
![Twitch_Negative](https://github.com/cedricr/100joursdezbeul/assets/133201336/7c67fb83-0e5c-42fd-9d5c-8bef79ab8525)
![Facebook_Negative](https://github.com/cedricr/100joursdezbeul/assets/133201336/84eed0ce-9b2e-4c4d-bb8a-0100048659e3)
![Twitter_Negative](https://github.com/cedricr/100joursdezbeul/assets/133201336/cdebc1a0-a0cd-4430-b7b7-4de85da14ac3)
![Mastodon_Negative](https://github.com/cedricr/100joursdezbeul/assets/133201336/98d6608e-833c-4279-bff8-85815c5dda8c)

**Comment by D4llo** [comment]
Pour les icônes de ce type j'aime bien https://simpleicons.org/ (où j'ai déjà contribué)

**Comment by D4llo** [comment]
J'ai ajouté la couleur au hover

![image](https://github.com/cedricr/100joursdezbeul/assets/131776117/8cf8f0ec-50a0-4b94-be3b-cf990706665e)


![image](https://github.com/cedricr/100joursdezbeul/assets/131776117/2dc4fc7f-02f9-4670-8fa6-a7f3d80b6abf)

**Comment by CharligaUX** [comment]
> Pour les icônes de ce type j'aime bien https://simpleicons.org/ (où j'ai déjà contribué).
> 
> Est-ce que le `<p>Vous pouvez nous retrouver sur :</p>` est vraiment utile ?



> J'ai ajouté la couleur au hover
> 
> ![image](https://user-images.githubusercontent.com/131776117/237833090-8cf8f0ec-50a0-4b94-be3b-cf990706665e.png)
> 
> ![image](https://user-images.githubusercontent.com/131776117/237832965-2dc4fc7f-02f9-4670-8fa6-a7f3d80b6abf.png)

Top la librairie, et très  sympa les hover.
Je laisserai l’intertitre pour éviter que ça flotte trop. 
allez : au dodo !

**Comment by D4llo** [comment]
J'ouvre la MR et je vais me coucher. Bonne nuit et merci pour les retours !

**Comment by CharligaUX** [comment]
… que l’inter-contrat / mission serve un peu à ça : avec plaisir !
