### ISSUE TITLE
Améliorer l'accessibilité des caractéristiques d'un caractértistiques

### ISSUE THREAD

**Issue by CharligaUX** [cedricr/100joursdezbeul#119]
Augmenter la taille de la police pour les données sur un event pour les données : 
Type d'actions
Personnalités
Liens (twitter ou web)

**Comment by D4llo** [comment]
Ok pour augmenter dans l'idée. Une préférence ?

font-size 0.75rem, line-height: 1rem (actuel)

![image](https://github.com/cedricr/100joursdezbeul/assets/131776117/6378efa8-0fb0-45b4-8553-c6666b76338d)

font-size 0.85rem, line-height: 1.1rem (1ere proposition)

![Screen Shot 2023-05-11 at 13 07 57](https://github.com/cedricr/100joursdezbeul/assets/131776117/9de8c2a2-b714-4b46-ba45-e219d6799b8d)

font-size 0.95rem, line-height: 1.2rem (2e proposition)

![Screen Shot 2023-05-11 at 13 09 48](https://github.com/cedricr/100joursdezbeul/assets/131776117/bbc8a82e-43d4-4f11-b549-b75276803b50)

Cela devrait aussi améliorer l'a11y. Qu'en penses-tu @juliemoynat ?

**Comment by D4llo** [comment]
Je viens de voir qu'on utilisait `text-xs` du coup je propose de passer en `text-sm`:

![image](https://github.com/cedricr/100joursdezbeul/assets/131776117/388aa620-d832-44ff-8878-a2bd754550b0)

**Comment by CharligaUX** [comment]
Oui, text-sm me parait suffisant, pour le distinguer du contenu au dessus.
mais je laisse Julie décider. :)
(en général pour le mobile on ne descend pas en dessous de 14px - certains disent même 16)

**Comment by juliemoynat** [comment]
Alors, il n'y a pas vraiment de règle précise si ce n'est que dans les champs de formulaire, si la taille de police est de moins de 16px, sur iOS, ça zoome la page donc, effectivement, j'ai tendance à recommander au moins pour les champs de formulaire de ne pas être en dessous de 16px.

Ici, clairement, les 12px c'est vraiment très petit donc aucun soucis pour augmenter. Entre 14px ou 16px, je dirais que si on passe à 16px comme le texte au-dessus, il faudra repenser le design donc partons déjà sur 14 et voyons plus tard si on fait mieux 😉
