### ISSUE TITLE
page de classement : permettre un filtre des events pour trouver une Personnalité

### ISSUE THREAD

**Issue by CharligaUX** [cedricr/100joursdezbeul#121]
Ex : toute les actions réalisées, tous départements confondus pour Pap Ndiaye.

Et si trop complexe (pas de base de données nominative), proposer la fonctionnalité par "catégorie personnalité" telle que dans le règlement : 

Village du SNU 
Secrétaire d’État 
Ministre délégué·e 
Ministre 
Ministre de l’intérieur 
Présidente de l’Assemblée nationale 
Première ministre 
Président de la République

**Comment by D4llo** [comment]
J'aime beaucoup l'idée à voir comment on peut mettre ça en place

**Comment by CharligaUX** [comment]
Saurais-tu me dire quelle bibliothèque d’icon est utilisée (pour les médailles?).
J’aimerais proposer un rendu (front) pour l’affichage de ce filtre (associé à un total d’Events).

**Comment by florianMo** [comment]
Il s'agirait de filtrer le classement principal sur les personnalités ou type d'actions ? Est ce que ça ne serait pas plus pertinent sur une liste de toutes les actions (non agrégées par depts) ?

**Comment by CharligaUX** [comment]
J'étais partie sur un filtre Personnalité sur toutes les actions (classement principale), mais s'il est bien positionné, on pourrait cumulé le filtre département ET ce filtre Personnalité... et pourquoi pas en effet ajouter aussi un filtre sur le type d'action (ca en ferait 3). J'aimerai faire une maquette vite fait

**Comment by D4llo** [comment]
> Saurais-tu me dire quelle bibliothèque d’icon est utilisée (pour les médailles?).
> J’aimerais proposer un rendu (front) pour l’affichage de ce filtre (associé à un total d’Events).

Je ne sais pas  si une collection particulière à été utilisé Je laisse la parole à @juliemoynat qui pourra mieux répondre.

**Comment by juliemoynat** [comment]
Nope, pas de bibliothèque d'icônes, c'est du fait maison 😁 mais il y a les SVG dans le projet donc pour celles déjà créées, c'est possible de travailler avec et s'il en faut d'autres, possible de les créer (si besoin, je peux aider sur ça) ou d'utiliser des icônes libres existantes.

**Comment by florianMo** [comment]
merci pour les maquettes @CharligaUX ! En effet ça pourrait être sympa, on pourrait tester déjà sur une propriété (rôle de la personne par exemple). Etendre ensuite à une autre propriété ne devrait pas représenter beaucoup de travail en plus.

**Comment by CharligaUX** [comment]
Hello ! 
J'ai continué la réflexion hier soir,... sur la version Mobile et la maquette donnerait plutôt ça (hors échange à avoir par ailleurs  - peut-entre - sur le choix assumé ou évolutif de réduire la taille du header).
Et le chiffre en vert à mettre dans la police du Zbeul ;) (mais je ne l'ai pas)
![TRI_100joursdezbeul fr MOBILE](https://github.com/cedricr/100joursdezbeul/assets/133201336/dfafb0de-4be4-472a-aa42-5c541a8d5a4d)

**Comment by florianMo** [comment]
A quoi serviraient les liens "Par département" et "Par date" ? Ca donne l'impression que c'est un mode de tri, or ici on triera toujours par score des depts non ? Ou alors tu imagines de calculer les score par date et de classer des jours selon le nombre de points total marqués sur une journée ? Si c'est bien ça, autant ajouter la possibilité de trier sur la page calendrier je pense.

**Comment by CharligaUX** [comment]
Par date, c'est la vue Calendrier,... mais c'est pas encore satisfaisant

**Comment by D4llo** [comment]
> Ensuite, on aurait la recherche full texte (ex : Pap Ndiaye), qui utiliserait le même affichage que sur un département : la liste détaillée,... avec un total de score.

J'ai fait ça #128
