### ISSUE TITLE
Contenus : pourrait-on fusionner les pages Règles du Jeu & Participer ?

### ISSUE THREAD

**Issue by CharligaUX** [cedricr/100joursdezbeul#127]
Elles sont très proches et complémentaires. 
Je peux faire une proposition de texte si ok pour vous.

**Comment by juliemoynat** [comment]
Ça me semble être une bonne idée. On aurait plus qu'une page "Règle du jeu" au final.

Reste à voir comment articuler ça pour ne pas faire une page trop longue et conserver de la clarté (sans faire trop compliqué du point de vue design aussi).

**Comment by CharligaUX** [comment]
Question pour la rédaction de la page unique : 
Dans la page : https://100joursdezbeul.fr/comment-participer  > section Actions non prises en compte > il y a une phrase qui dit : "Les actions sur la caravane du SNU sont bien comptabilisées." => est-ce que ca a vraiment besoin d'être précisé, puisque c'est le 1er de la liste des "personnalités" (de ma compréhension) ? où est-ce autre chose ? @juliemoynat @D4llo @cedricr

**Comment by juliemoynat** [comment]
C'est précisé ici car, auparavant, le SNU n'était pas comptabilisé et la phrase était donc négative 😉

**Comment by D4llo** [comment]
Dans la section personnalité, est-ce que ce serait bien d'ajouter un lien vers la page personnalité ?

cc #73

**Comment by CharligaUX** [comment]
Ça donnerait ça :)
![100joursdezbeul fr_Regles_Desktop](https://github.com/cedricr/100joursdezbeul/assets/133201336/6d71c63c-8c1e-4c30-bceb-6e55d7bdd5dc)
![100joursdezbeul fr_Regles_MOBILE](https://github.com/cedricr/100joursdezbeul/assets/133201336/00461219-7b8d-4479-a360-34fbb4dd2e0b)

**Comment by juliemoynat** [comment]
Super travail @CharligaUX ! Merci beaucoup !

@cedricr si jamais tu t'en charges avant moi, suite à notre discussion d'hier, je pense qu'on devrait écrire "point"/"points" en toutes lettres au lieu de l'abréviation pour que ce soit plus lisible 😉

**Comment by CharligaUX** [comment]
👏🏻

**Comment by cedricr** [comment]
> Super travail @CharligaUX ! Merci beaucoup !

Je plussoie ;-) Merci beaucoup!
