### ISSUE TITLE
Ajouter une page pour les personnalités

### ISSUE THREAD

**Issue by D4llo** [cedricr/100joursdezbeul#128]
Hello

Ça vous dirait de faire une page regroupant les participations des personnalités ?

Pour le moment j'ai ça:

https://github.com/cedricr/100joursdezbeul/assets/131776117/92bc9adf-2750-402c-9d27-b030940101a5

Cela ajoute le nom des personnes dans les évènements

![image](https://github.com/cedricr/100joursdezbeul/assets/131776117/8e4426af-bee5-4b7e-b562-6ff888728b41)

et des pages individuelles:

![image](https://github.com/cedricr/100joursdezbeul/assets/131776117/810ef50c-e5c2-4771-9953-d9109a17b587)

**Comment by D4llo** [comment]
Bonus si pour chaque personnalité, on arrive à avoir un lien vers un site gouvernemental, wikipedia, [lescasseroles.fr](https://www.lescasseroles.fr/les-politiques/eric-dupond-moretti), et un site du genre nosdeputes.fr

Ce serait cool d'ajouter aussi les réseaux sociaux des personnalités pour permettre de créer du lien entre chaque personne et sa base électorale.

**Comment by CharligaUX** [comment]
Whouhaou, c’est top ! Bravo

**Comment by D4llo** [comment]
@CharligaUX Merci à toi pour avoir lancer l'idée ! :smile:

**Comment by D4llo** [comment]
Note que j'utilise un export scrapé du site https://www.gouvernement.fr/composition-du-gouvernement

Mais du coup il y a des doublons pour les personnes faisant deux jobs:

![image](https://github.com/cedricr/100joursdezbeul/assets/131776117/7437f842-cc9a-4593-802a-e232e234d98b)

**Comment by D4llo** [comment]
Les cas vides ne sont pas gérés :

![image](https://github.com/cedricr/100joursdezbeul/assets/131776117/854108a8-39a1-4591-9801-e82bd6bbdb33)

Quel message sympathique afficher ?

**Comment by D4llo** [comment]
Page globale

![image](https://github.com/cedricr/100joursdezbeul/assets/131776117/eeded1d2-ec5f-4041-8cc4-faef9453cabd)

**Comment by CharligaUX** [comment]
> Les cas vides ne sont pas gérés :
> 
> ![image](https://user-images.githubusercontent.com/131776117/238092424-854108a8-39a1-4591-9801-e82bd6bbdb33.png)
> 
> Quel message sympathique afficher ?

Suggestion : Aucun Zbeul au [date du …] (date des data / comme la page d’accueil)
+ ajouter bouton Ajouter un événement

**Comment by CharligaUX** [comment]
> Note que j'utilise un export scrapé du site https://www.gouvernement.fr/composition-du-gouvernement
> 
> Mais du coup il y a des doublons pour les personnes faisant deux jobs:
> 
> ![image](https://user-images.githubusercontent.com/131776117/238088103-7437f842-cc9a-4593-802a-e232e234d98b.png)
> 
> Sarah El Haïry est aussi concerné

Arf,… le cumul des mandats : 
C’est logique dans la liste mais est-ce dans la page détail du profil on peut agréger ?
