### ISSUE TITLE
Ajouter des scores sur les pages départements et personnalités

### ISSUE THREAD

**Issue by D4llo** [cedricr/100joursdezbeul#130]
Une sorte de mixte entre #128 et #20 

![image](https://github.com/cedricr/100joursdezbeul/assets/131776117/5c9339c9-8be3-41ce-9703-db75d8ad19a3)

Qu'en pensez-vous ?

**Comment by CharligaUX** [comment]
C’est pas mal mais au max on peut avoir 6 types d’action… 6 ronds ça risque de ne pas rentrer autrement que sur 2 lignes sur mobile. A tester.
Peut-être mettre les chiffres dans couleur pour un peu de fun.. extraite de celles du logo ?
Et/ou un total en chapo ?

**Comment by CharligaUX** [comment]
Hello,
Voici 2 essais : 
> V1 : mobile et desktop avec les 6 types d'actions (le max) en me basant sur ta maquette au dessus : **les casseroles sont des nbrs d'évènements**
> V2 : variante, le postula : la casserole est le nombre de points générés par la sommes des événements (d'ou reprise du code couleur rouge : variantes mobile tout rouge, variante desktop casserole noire.)

**Perso je trouve que la V2 est plus alignée avec la logique des scores. :)**

![100joursdezbeul fr MOBILE_Scores_Perso](https://github.com/cedricr/100joursdezbeul/assets/133201336/de53c347-c3ad-4947-9dd0-40cb9ce56abf)
![100joursdezbeul fr DESKTOP_Scores_Perso](https://github.com/cedricr/100joursdezbeul/assets/133201336/f44e3018-ec55-414b-a8d9-d2e431c83968)![100joursdezbeul fr DESKTOP_Scores_Perso V2](https://github.com/cedricr/100joursdezbeul/assets/133201336/85ead10b-d22e-49a0-b680-ebfb48fe7bbb)
![100joursdezbeul fr MOBILE_Scores_Perso V2](https://github.com/cedricr/100joursdezbeul/assets/133201336/b806a47f-cf60-4b38-845f-56a0bb7af9bc)

**Comment by D4llo** [comment]
C'est pas très inspiré mais on peut recycler la liste de la page statistique nationale 
![image](https://github.com/cedricr/100joursdezbeul/assets/131776117/86cfbe0a-f601-43d4-a6b2-5184e2af59e7)

https://100joursdezbeul.fr/statistiques
