### ISSUE TITLE
Valoriser le lien Signaler une action ?!

### ISSUE THREAD

**Issue by CharligaUX** [cedricr/100joursdezbeul#131]
Question de stratégie et capacité à faire…
Mais il est bien planqué dans le footer. (Choix?)
Ça pourrait être intéressant de le passer en bouton + visible et de le positionner plus haut (soit juste en dessous des résultats affichés soit dans la navigation)…

**Comment by juliemoynat** [comment]
Je suis d'accord, je me suis fait la réflexion hier en le cherchant… je le trouvais pas !

**Comment by cedricr** [comment]
Oui le problème c'est qu'on reçoit beaucoup de sollicitations et double inutiles, puisque qu'on récupère déjà l'immense majorité des données via Attac... Et on a beau bloquer la date du jour sur le formulaire, et expliquer le raisonnement en dessus, les gens pensent que c'est un bug, et soumettent quand même avec une date incorrecte... :shrug: Mais bon, en tout cas on ne résout pas un problème en cachant les choses, donc ok sur l'évolution!
