### ISSUE TITLE
Mettre les remerciements dans les mentions légales

### ISSUE THREAD

**Issue by juliemoynat** [cedricr/100joursdezbeul#132]
Je trouve que le bas de la page d'accueil fait brouillon (mais c'est normal puisqu'on enrichit le site au fur et à mesure). Il me semblerait plus pertinent de mettre des remerciements dans la page "Mentions légales" qu'on pourrait renommer "Mentions légales et crédits".

Qu'en pensez-vous ?

**Comment by cedricr** [comment]
tant qu'on garde l'icone Solidaires Informatique qq part sur la home page oui, carrement!
