### ISSUE TITLE
Que disent les stats de consultation Mobile VS Desktop ? => optimiser le header ?

### ISSUE THREAD

**Issue by CharligaUX** [cedricr/100joursdezbeul#139]
Si la part sur mobile est importante, je trouve que ca vaudrait e coup d'avoir un header qui ne fait pas (quasi) la hauteur de l'écran... 
Perso, moi, ca me gène un peu de devoir scroller pour consulter du contenu. A fortiori avec l'augmentation des pages proposées.

Aussi, je suggère les maquettes suivantes : sur desktop un logo avec une hauteur de 80 VS 50px sous mobile.
La maquette est faite au format iPhone SE.

![Header_device=mobile](https://github.com/cedricr/100joursdezbeul/assets/133201336/134aa998-9824-4acb-8a4a-45fb30fc16df)
![Header_device=desktop](https://github.com/cedricr/100joursdezbeul/assets/133201336/41d54a39-f0f8-412d-a864-6879ab1e5a07)

**Comment by CharligaUX** [comment]
👌🏻👏🏻

**Comment by cedricr** [comment]
Merci pour toutes tes suggestions @CharligaUX !
