### ISSUE TITLE
Réorganiser les différentes vues des Scores ?

### ISSUE THREAD

**Issue by CharligaUX** [cedricr/100joursdezbeul#140]
Hello,
Je vous partage une observation, maintenant que nous avons différentes vues : je m'y perds un peu dans la "navigation".

Voilà un draft de solution pour vous partager ma pensée (pas aboutie), qui part du postulat qu'on aurait  **UNE seule page SCORES**, sur laquelle on pourrait appliquer des filtres(autres points)... mais surtout **qui permet de choisir le mode d'affichage du classement entre** : Département (par défaut), Régions (à venir), pays (stats nationales), dates (calendrier actuel), personnalité (nouvelle vue), actions (suggestion de nouveauté) :

[SCORES - VUES.pdf.zip](https://github.com/cedricr/100joursdezbeul/files/11479256/SCORES.-.VUES.pdf.zip)

**Comment by CharligaUX** [comment]
@juliemoynat : ton avis ?

**Comment by juliemoynat** [comment]
Sur le principe, pourquoi pas. On a une discussion en cours sur si on met du JS ou pas dans le site donc on va attendre cette décision pour voir comment et si on fait ça.

**Comment by cedricr** [comment]
@CharligaUX (je n'ai pas encore regardé ton PDF, mais un premier avis néanmoins): 
oui sur le moyen terme, il faut simplifier la navigation, et les filtres seront peut-être la réponse. Mais dans l'immédiat, on a pas mal de vues différentes, et on est sans doute sur le point d'en rajouter d'autres (carte, score pondéré, régions...), sans avoir fait de recherche UX dessus, ni sans avoir une forte demande utilisateurice.
Dans un premier temps je préfère qu'on ait un pied de page un peu fourre tout, et des pages séparées qu'on peut partager sur les reseaux, pour pouvoir jauger un peu l'intérêt, plutôt que de trop complexifier la page d'accueil.

**Comment by CharligaUX** [comment]
@cedricr : merci pour ton retour, je comprends le souhait d'URL dissociées pour suivre les stats. 
Mais je trouve dommage de mettre "quasi" au meme niveau de visibilité les pages type Contact / mentions légales et les stats nationales et autres vues à venir... on pourrait pas mettre certains liens en haut ? Ca valoriserait le travail fait...

**Comment by juliemoynat** [comment]
Oui, on pourrait faire une sorte de menu secondaire sous le menu principal dans l'immédiat. C'est vrai que la page des stats est assez peu visible alors qu'elle est intéressante. Je m'assigne le ticket. Je regarderai ça dans le weekend.

**Comment by cedricr** [comment]
> @cedricr : merci pour ton retour, je comprends le souhait d'URL dissociées pour suivre les stats.

Je pensais plus à des retours utilisateurs qu'à des stats -- genre "c'est super de pondérer les scores", ou au contraire, personne ne nous en dit rien, mais sinon oui c'est l'idée!
