### ISSUE TITLE
Ajout d'un "département" Pétitions

### ISSUE THREAD

**Issue by ofa-** [cedricr/100joursdezbeul#26]
Lo guys,

y'a zbeul _aussi_ dans l'internet des pétitions ; ça vaut peut-être un "département pétitions (P)" dédié.

Exemples de zbeul pétitionaire :
- sur le site [petitions.assemblee-nationale.fr][petitions AN], au moins 2 candidates déjà en course,
- probablement d'autres sur change.org - j'ai pas cherché

Pour refléter ce zbeul là, je propose d'ajouter un département "pétitions", une sorte de "département internet virtuel", un peu comme un DOM, mais numérique.

Si ça peut le faire, faudrait sans doute inventer un scoring différent des actions physiques ; ou mettre le "département pétitions" hors-compétition.

[petitions AN]: https://petitions.assemblee-nationale.fr/initiatives?order=most_voted

**Comment by D4llo** [comment]
Pas évident de relier ces pétitions à un département en particulier. Néanmoins cela fait monter le zbeul générale, donc je les mettrais bien en avant dans les stats nationales discuté sur #20

**Comment by fambon** [comment]
> ça vaut peut-être un "département" dédié.

je proposais carrément ajouter un département "pétitions", une sorte de "département internet virtuel".
un peu comme un DOM, mais numérique.

**Comment by ofa-** [comment]
> ça vaut peut-être un "département" dédié.

je proposais carrément ajouter un département "pétitions", une sorte de "département internet virtuel".
un peu comme un DOM, mais numérique.

**Comment by ofa-** [comment]
Pour les 2 candidates du site de l'assemblée, shameless auto-promo : https://github.com/ofa-/poll-tac/

Les graphes de suivi sont utilisables directement en tant qu'images (cf [le README](https://raw.githubusercontent.com/ofa-/poll-tac/master/README.md)) ou en mode interactif (changer `format=image` en `format=interactive` dans les url) ; sinon les données brutes sont dispo pour re-utilisation (update toutes les 10 minutes environ via [github action](https://github.com/ofa-/poll-tac/blob/master/.github/workflows/main.yml)).

**Comment by ofa-** [comment]
update : suivi de pétitions assemblée nationale déplacé => [politipet.github.io](https://politipet.github.io)

**Comment by cedricr** [comment]
Franchement c'est une bonne idée, mais ça mérite un projet à part !

**Comment by ofa-** [comment]
ouais, ou tout simplement, ajouter un lien vers https://politipet.github.io ? zero coût d'intégration ; co-branding.

**Comment by ofa-** [comment]
PS: celle [à la fraise](https://politipet.github.io/#1590) est très bonne (je trouve).

**Comment by ofa-** [comment]
a la réflexion, CLOSED is CLOSED, donc on ne discute pas.
j'efface ce message et les précédents.

Merci, et bonne route !
