### ISSUE TITLE
Fil de discussion concernant le barème Personnalités

### ISSUE THREAD

**Issue by adbar** [cedricr/100joursdezbeul#3]
Bonjour, merci pour cette initiative !

Je me permets d'ouvrir une discussion concernant le barème autour des points suivants, à compléter si besoin est. Dans l'ensemble s'agit de récompenser des actions de moindre envergure mais bien réparties. C'est en soi une question à débattre mais de nombreuses interruptions valent en principe mieux qu'une seule action largement médiatisée et rien d'autre.

- Quid des députés et/ou responsables de parti ? suggestion : rang comparable aux Secrétaires d’État ?
- Quid des acteurs économiques, syndicats patronaux, etc. ?
- Secrétaires d’État / Ministre délégué·e / Ministries : différence de 1 à 3 pas forcément pertinente selon les fonctions. Trois personnalités empêchées valent bien un·e ministre...
- Normalisation des points par nombre d'habitants ? La Lozère part perdante selon les règles actuelles, il faudrait trouver un mécanisme pour compenser.

**Comment by D4llo** [comment]
> Quid des députés et/ou responsables de parti ? suggestion : rang comparable aux Secrétaires d’État ?

Ça me va si iels ne se sont pas opposées publiquement à la réforme des retraites.

> Quid des acteurs économiques, syndicats patronaux, etc. ?

Ça me va si iels ne se sont pas opposées publiquement à la réforme des retraites. Il va falloir peut-être faire une liste publique des personnes concernées.

> Secrétaires d’État / Ministre délégué·e / Ministries : différence de 1 à 3 pas forcément pertinente selon les fonctions. Trois personnalités empêchées valent bien un·e ministre...

Je pense qu'on chipote. Je n'ai pas d'avis tranché perso.

> Normalisation des points par nombre d'habitants ? La Lozère part perdante selon les règles actuelles, il faudrait trouver un mécanisme pour compenser.

+1 pour normaliser par quantité usuelle de venue dans chaque département. On doit pouvoir sortir ces datas.

----

J'aimerai savoir ce que nous souhaitons faire des actions interdites par les autorités ?

[Déplacement de Macron : une loi antiterroriste de nouveau utilisée pour interdire une manifestation à Vendôme](https://www.liberation.fr/checknews/deplacement-de-macron-une-loi-anti-terroriste-de-nouveau-utilisee-pour-interdire-une-manifestation-a-vendome-un-refere-liberte-a-ete-depose-20230425_3F5Z5XKDWFCCNGYJ7TVTQGVLOA/)

Je propose de donner la moitié des points prévu, soit `(chahut + manif) * président / 2 <=> 2 * 6 / 2 <=> 6pts`.

J'aimerai aussi ajouter une target vide/libre : 

```ts
export const TARGET_MULTIPLIER = {
	'libre': 0,5,
	'secretaire-etat': 1,
	'ministre-del': 2,
	ministre: 3,
	'ministre-int': 4,
	'presidente-an': 4,
	'premiere-min': 5,
	'president-rep': 6
};
```

Cela nous permet de soutenir ce genre d'action: [Réforme des retraites. 500 personnes défilent au son des casseroles à Nantes](https://www.ouest-france.fr/economie/retraites/500-personnes-defilent-au-son-des-casseroles-a-nantes-a9e7cb0c-e2c9-11ed-b514-8dd13d8be671)

**Comment by cedricr** [comment]
Merci de vos suggestions!

Pour la normalisation, c'est prévu oui!
Pour les autres types de personnalités, on est assez chaud, mais c'est beaucoup plus de boulot de récupération et de traitement de données. Ça va sans doute venir!

**Comment by cedricr** [comment]
Pour la pondération j'ai créé https://github.com/cedricr/100joursdezbeul/issues/87

**Comment by D4llo** [comment]
Une fois qu'on a fini de split cette issue, on peut la fermer.

**Comment by cedricr** [comment]
On ne va pas ajouter d'autres types de personnalité ou d'action dans l'immediat, et les modifications de barême à ce stade n'ont pas forcement beaucoup de sens. 
La normalisation des données vit sa vie dans une autre ticket
