### ISSUE TITLE
Publier aussi les evenements à venir dans les pages des départements

### ISSUE THREAD

**Issue by fambon** [cedricr/100joursdezbeul#40]
Je comprends bien que « ça compte les points » donc _après coup_, logique.

Mais.

Je me suis confusioné en utilisant la liste _aussi_ comme agenda - cf la source de données chez Attac, qui est à la fois un log et un agenda.

La liste des top scores offre en fait un browsing transversal de l'agenda de Attac, par département ; c'est plus pratique que leur page par dates pour surveiller ce qui va arriver près de chez vous.

Je me demandais du coup si y aurait pas quand même un interêt à re-publier la partie "agenda" des données i.e. afficher les évènements "en avance" aussi dans les pages de départements ; avec un scoring à zero ou "en attente de résultat".

**Comment by D4llo** [comment]
Pour moi, l'idéal est d'encourager le plus possible à organiser local. C'est à dire à contacter et avancer avec les syndicats de votre région (idéalement syndiquez vous, le [syndicalisme c'est cool ](https://syndicalisme.cool/). Attac est bien sûr présent partout en France. Voici leur carte des comités locaux : https://france.attac.org/attac/les-comites-locaux/. Les mouvements politiques que ce soit des partis ou non sont aussi des canaux d'organisation.

**Comment by juliemoynat** [comment]
J'adore l'idée d'ajouter des évènements "en attente de résultats". Je trouve que ça aurait totalement sa place dans l'idée de présenter les actions de zbeul par jour (ticket #94), en plus.

**Comment by cedricr** [comment]
On pourra peut-être récupérer plus facilement les données Attac dans le futur, mais je trouve que ça fait double emploi avec leur site: nous on compte les points, eux s'occupe du recensement et de la mobilisation.
À mon avis on peut fermer ça dans l'immédiat.

**Comment by juliemoynat** [comment]
Ça me va de fermer, surtout qu'on va ajouter un lien vers le site d'Attac dans le menu pour aller chercher où zbeuler.
