### ISSUE TITLE
Ajouter une "heatmap" carte de france des départements

### ISSUE THREAD

**Issue by fambon** [cedricr/100joursdezbeul#41]
suggestion graphique : montrer les scores des départements sur une carte de France façon "heatmap"

**Comment by fambon** [comment]
ou, dit autrement, une carte météo du zbeul :grin: 

restera plus qu'a trouver un présentateur pour faire la séquence quotidienne sur télé-zbeul

**Comment by AshbyDeLaZouche** [comment]
Je peux essayer de le coder avec chart.js et le plugin geo.

**Comment by D4llo** [comment]
@AshbyDeLaZouche let's go! tu peux la mettre sur la page d'accueil sous le classement.

**Comment by AshbyDeLaZouche** [comment]
@D4llo merci de me donner accès en écriture au repo. Pour que je puisse publier une PR. J'ai une première version et j'aimerais la partager pour avoir des feedback et l'améliorer.
Voilà à quoi ça ressemble:
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/132066367/235287640-9b150b52-d3f9-481c-b2ef-a0e2fa5b9898.png">

**Comment by D4llo** [comment]
@AshbyDeLaZouche tu n'as pas besoin des accès au repo pour ça. Tu fais un fork en [cliquant ici](https://github.com/cedricr/100joursdezbeul/fork), travaille sur ton repo et ensuite tu ouvres une PR vers ce repo.

**Comment by AshbyDeLaZouche** [comment]
merci @D4llo 
Je suis entièrement d'accord avec ta suggestion pour le titre. 
J'ai publié la PR #57

**Comment by fambon** [comment]
pour le titre, y'a aussi moyen de carrément pas en mettre ; c'est auto-descripif, une carte de France des départements juste sous un hall-of-fame, non ?

Question : c'est clickable ? hoverable ?

**Comment by AshbyDeLaZouche** [comment]
Oui ce sera bientôt clickable et déjà hoverable. Pour le titre, disons que ça permet de séparer les sections ... mais je suis d'accord ça se discute.

**Comment by AshbyDeLaZouche** [comment]
Preview disponible [ici](https://deploy-preview-57--100joursdezbeul.netlify.app/)

**Comment by AshbyDeLaZouche** [comment]
Les Départements sont clickables

**Comment by fambon** [comment]
et sinon, pour "juste une carte" (donc pas avec heatmap)  y a l'option iframe en direct depuis chez Attac :

----

<iframe width="800px" height="600px" frameborder="0" allowfullscreen src="http://umap.openstreetmap.fr/fr/map/casseroleschallenge_901322?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=undefined&captionBar=false&datalayers=2754530%2C2754532#6/46.860/0.967"></iframe>

----

celle là montre les actions passées et visites annulées (i.e. pas les "prévues" - ça simplifie la vue).

C'est probablement un peu plus lourd au chargement que la version @AshbyDeLaZouche, ça ne groupe pas par départements et ça ne montre pas explicitement une heatmap - mais ça en donne une idée quand même, tous ces boutons rouges (et oranges) genre éruption cutanée :-)

Je me dis que ça a peut-être sa place quelque-part sur le site ?

**Comment by AshbyDeLaZouche** [comment]
> et sinon, pour "juste une carte" (donc pas avec heatmap) y a l'option iframe en direct depuis chez Attac :
> 
> <iframe width="800px" height="600px" frameborder="0" allowfullscreen src="http://umap.openstreetmap.fr/fr/map/casseroleschallenge_901322?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=undefined&captionBar=false&datalayers=2754530%2C2754532#6/46.860/0.967"></iframe>
> celle là montre les actions passées et visites annulées (i.e. pas les "prévues" - ça simplifie la vue).
> 
> C'est probablement un peu plus lourd au chargement que la version @AshbyDeLaZouche, ça ne groupe pas par départements et ça ne montre pas explicitement une heatmap - mais ça en donne une idée quand même, tous ces boutons rouges (et oranges) genre éruption cutanée :-)
> 
> Je me dis que ça a peut-être sa place quelque-part sur le site ?

Excellent ! Je pense qu'on pourrait au moins avoir un lien sur le site
