### ISSUE TITLE
Erreur possible avec les emoji

### ISSUE THREAD

**Issue by D4llo** [cedricr/100joursdezbeul#52]
Sur chromium sous Linux je n'ai pas les emojis (tout marche bien sur Firefox)

![image](https://user-images.githubusercontent.com/131776117/235242268-33b2d0e1-2923-4879-ae2f-1d65a4bf3a66.png)

C'est peut être rien mais je note ça au cas où

**Comment by juliemoynat** [comment]
Sinon, on choppe des icônes SVG ?

**Comment by D4llo** [comment]
@juliemoynat où on les dessine en CSS ? Tout me va :)

**Comment by juliemoynat** [comment]
![medaille-or](https://user-images.githubusercontent.com/6296770/235354805-34f37674-463e-475b-8891-97f954202dd5.svg)
![medaille-argent](https://user-images.githubusercontent.com/6296770/235354807-d277bdf8-408e-4485-bf22-a31d2927aa1e.svg)
![medaille-bronze](https://user-images.githubusercontent.com/6296770/235354809-167b653d-2ab1-46ba-a014-2932c15e08cc.svg)

Tiens, j'ai fait des SVG rapido (c'est plus facile pour moi 😛). Qu'en dis-tu ?

**Comment by cedricr** [comment]
@D4llo pour info, tu peux résoudre ça en installant la bonne fonte (Noto Color Emoji par exemple), mais tu ne seras pas le seul dans ce cas, donc la solution svg reste interessante! On a d'autres emoji sur le sites qui poseront le même problème, mais ils sont moins centraux, je pense qu'on peut les ignorer,

**Comment by D4llo** [comment]
Bon pour moi pour les svg. Tout en sachant que je pense que tous les devices de nos jours ont une police d'emoji et qu'utiliser des emoji evite de surcharger la page avec du contenu supplémentaire à charger.

Comme vous voulez :smiley:

**Comment by cedricr** [comment]
Ben c'est toi qui n'arrivait pas à les afficher, hein ;-)
Hors Linux, le problème n'existe pas. Sur Linux il est facile à régler, mais ça peut arriver. Je suis pas fan de les remplacer partout, pour les raisons que tu donne. Pour la home page, c'est trois petits fichiers, et c'est des symboles important, donc je suis +0 sur l'issue.

**Comment by D4llo** [comment]
@cedricr sur chromium uniquement et pas sur FF. Vu que j'utilise quasiment jamais chromium, je m'en fiche un peu.

**Comment by juliemoynat** [comment]
Dans la mesure où le problème peut se produire, je préfère qu'on le prenne en compte car il s'agit de quelque chose d'important ici. Je fais une PR.
