### ISSUE TITLE
Je mettrais plutot un '-' ou rien plutot que répeter le rang mais c'est probablement moins bien niveau accessibilité et peut etre un peu plus chiant à gérer donc ça peut venir dans un 2e temps

### ISSUE THREAD

**Issue by D4llo** [cedricr/100joursdezbeul#54]
Je mettrais plutot un '-' ou rien plutot que répeter le rang mais c'est probablement moins bien niveau accessibilité et peut etre un peu plus chiant à gérer donc ça peut venir dans un 2e temps

_Originally posted by @anonymousDuZbeul in https://github.com/cedricr/100joursdezbeul/pull/49#discussion_r1180628587_

**Comment by fambon** [comment]
et pourquoi pas mettre le nº du département (entre parenthèses) aucu, aucu, aucu du nom complet ?

**Comment by juliemoynat** [comment]
Moi je mettrais un signe "=" plutôt qu'un tiret car ça évite de se dire "ce département n'a pas de rang", tout en précisant en texte masqué en CSS pour les personnes aveugles "4 ex aequo".

@fambon je n'ai pas compris ton commentaire 🤔

**Comment by fambon** [comment]
@juliemoynat j'ai clarifié mon commentaire :-)

**Comment by juliemoynat** [comment]
@fambon ah merci ! Je pense que c'est une bonne idée d'ajouter le numéro du département mais je le verrais plus entre parenthèses après son nom car, dans le rang, ça porterait vraiment à confusion.

**Comment by cedricr** [comment]
@juliemoynat d'un coté je suis complètement pour par ce que ça manque vraiment, de l'autre je trouve que ça fait quand même une grosse succession de chiffres; est-ce que ce n'est pas un peu confus?
Je pourrais peut-être augmenter un peu la largeur du tableau pour que ça devienne moins étriqué?
![image](https://user-images.githubusercontent.com/7826756/236615826-c4b0889b-7282-4694-ac60-a760fd9cbd53.png)

**Comment by cedricr** [comment]
Et est-ce qu'on le mettrait partout, ou seulement sur le classement? Sur la page departements aussi ça me parait un peu confus: 
![image](https://user-images.githubusercontent.com/7826756/236616045-3eb565ae-736a-4523-935e-ca33e978724c.png)

Page nouveauté: 
![image](https://user-images.githubusercontent.com/7826756/236616057-ea704b92-0073-4356-b36c-5fa73ea15f28.png)

J'aurais tendance à dire oui malgré tout, c'est vraiment utile.

**Comment by juliemoynat** [comment]
@cedricr je pense qu'il faut indiquer le numéro du département partout où on le nomme, oui (de façon automatisée en tout cas). Certaines personnes identifient plus le numéro que le nom donc ça aidera !

Perso, ça me choque pas dans le tableau mais, oui, tu peux augmenter la largeur (je l'avais déjà un peu élargi en faisant le tableau mais on peut encore !).
