### ISSUE TITLE
Ajouter un graph d'évolution sur chaque département

### ISSUE THREAD

**Issue by D4llo** [cedricr/100joursdezbeul#68]
L'idée ce serait de faire un line chart de la progression de points de chaque département

![image](https://user-images.githubusercontent.com/131776117/235350332-414a3a05-121e-450f-8370-647dabdef683.png)

https://www.chartjs.org/

**Comment by juliemoynat** [comment]
Il sera bien possible de générer une transcription textuelle automatique du graphique pour qu'il y ait une alternative accessible ? (J'imagine que oui mais je préfère soulever la question au cas où.)

**Comment by florianMo** [comment]
Bien motivé par ça, toujours d'actu @D4llo @cedricr ?

**Comment by D4llo** [comment]
Toujours d'actualité :+1:

**Comment by florianMo** [comment]
cool j'aime bien les graphes :)

**Comment by D4llo** [comment]
Yes pareil! De toute façon on rediscute toujours un peu en PR :)

**Comment by florianMo** [comment]
Oui je commencerai par décrire un peu mes idées et on verra où on va ! Mais basiquement, un line chart avec les progressions de chaque dept  + éventuellement une ligne pour le total me semble une bonne base.

**Comment by florianMo** [comment]
Ca pourrait aussi être un bar chart temporel, quelque chose comme ça (premier exemple trouvé :) ) : https://flourish.studio/visualisations/bar-chart-race/

**Comment by juliemoynat** [comment]
J'arrive pas à regarder l'exemple, ça bouge trop vite. C'est horrible 😱
Du coup, je sais pas ce que ça représente mais si c'est un truc animé, c'est non directement pour l'inaccessibilité du truc 😅

Je suis d'accord avec @cedricr que voir la progression des points n'apporte pas grand chose. La progression dans le classement, ce serait plus rigolo car on verrait la course entre les départements.

**Comment by florianMo** [comment]
Je suis pas spécialiste du sujet, mais est ce que l'enjeu de l'accessibilité impose de s'interdire tout ce qui n'a pas de fallback qui serait accessible à 100% des usagers ? J'ai l'impression que c'est une approche un peu extrême.

Ce genre de graphe animé permet justement en un coup d'oeil de voir l'évolution dans le temps du classement des départements (qui passe devant qui, quand, qui est au coude à coude, qui a percé à un moment précis...) ainsi que les écarts, et la dynamique de ces écarts. C'est très répandu dans la visualisation de données car ça permet de saisir les tendances et les ordres de grandeurs rapidement.

**Comment by juliemoynat** [comment]
OK, je comprends l'intérêt de ce type de graphique.

Toutefois, en tant que personne handicapée moi-même, recevoir un message qui dit que mon approche de l'accessibilité est extrême est, en l'occurrence, extrêmement violent.

Je vais donc expliquer mes propos précédents car je me doute que ce n'était pas l'objectif et que c'est certainement un manque de connaissance du sujet qui te fait tenir ces propos (tu n'es pas la première personne à les tenir en l'occurrence).

Concrètement, avoir un graphique qui bouge comme ça peut causer une impossibilité d'accès à l'information notamment pour les personnes souffrant de migraines ou ayant un trouble de l'attention, voire, selon la vitesse du mouvement, cela pourrait causer des crises d'épilepsie à des personnes épileptiques.

Quant aux personnes aveugles, nous serions probablement dans l'impossibilité de leur fournir une version alternative accessible puisque la mise à jour des données en mouvement rend la chose quasi-impossible voire impossible (on ne va pas leur faire une version texte qui bouge où leur lecteur d'écran lirait les données dès qu'elles changent, ce serait impossible à suivre… Noter ici que si c'est impossible à suivre avec les oreilles ou avec les doigts pour les personnes aveugles qui utilisent une plage Braille, c'est pareil pour les yeux.)

Concernant notre approche de l'accessibilité dans ce projet, elle consiste à faire en sorte que le site soit le plus accessible possible et respecte à minima la norme en vigueur (RGAA/WCAG). En tant que consultante en accessibilité web de par mon métier, je veille donc au grain à ce sujet et l'équipe est raccord avec ça. Il s'agit d'un projet militant, d'un syndicat militant qui cherche à s'orienter vers l'antivalidisme (tout n'est pas encore parfait mais on y travaille). C'est donc une valeur essentielle pour nous. (Nous allons ajouter une page "Accessibilité" qui expliquera tout cela car nous nous rendons compte que ça manque.)

Il faut bien prendre en considération que l'accessibilité est un droit humain pour les personnes handicapées qui ne sont pas des sous-humaines ou des sous-citoyennes. Par conséquent, ce qui est extrême n'est pas de considérer l'accessibilité comme un requis mais de discriminer, d'exclure des personnes. Pour creuser ce sujet un peu plus, j'ai écrit un texte qui s'appelle "[L'(in)accessibilité est politique](https://www.lalutineduweb.fr/inaccessibilite-politique/)" qui devrait aider à bien prendre conscience des enjeux.

En espérant que ça rend tout ça plus clair 😊

**Comment by florianMo** [comment]
Je suis complétement raccord avec tout ça également (notamment sur le fait que les médias animés sont très compliqués pour certains, et très compliqués à rendre accessibles), mais j'ai l'impression (je dis bien l'impression, je peux me tromper) que ton raisonnement précédent était "comme certaines personnes ne peuvent avoir pleinement accès à un élément de par leur condition, alors on s'interdit de l'utiliser" . Je comprends tout à fait que ce choix puisse être fait, ici ou sur d'autres projets, mais j'ai encore du mal à me dire que ça devrait devenir - moralement, politiquement... - une règle générale à suivre (dans la tech ou ailleurs). Je suis désolé si ça a pu te choquer, c'était bien évidemment pas mon intention. Je sais aussi que nous vivons dans un monde globalement validiste, même si je ne mesure surement pas pleinement ce que ça signifie.

Je suppose que l'idée serait de trouver des approches pour rendre accessibles ces choses (en me renseignant rapidement je lis qu'il y a des principes de base à respecter faute de permettre un accès complet à l'info), et donc je crois qu'au fond mon questionnement est bien celui là : est ce que, en attendant des solutions d'accessibilités là où elles manquent encore, on doit totalement renoncer à ce qu'on ne sait pas encore rendre accessible ? Ce serait une réponse affirmative à cette question qui me semble extrême aujourd'hui, et pas du tout "ton approche de l'accessibilité", que je ne me permettrai pas de juger.

Je vais de ce pas lire ton billet :).

**Comment by juliemoynat** [comment]
Oui, quand quelque chose n'est pas accessible, parfois on peut trouver une alternative accessible. Par exemple, pour un graphique sans mouvement, on fournira une version texte des données sous forme de liste ou de tableau (selon le type de graphique). Ainsi, une personne aveugle aura accès à l'information du graphique mais sous une forme qui lui est accessible.

Là, pour un truc en mouvement comme ça, la règle est "il faut pouvoir mettre en pause". Sauf que, comme tu le liras dans mon article, cette règle qui est très consensuelle ne répond pas réellement au besoin des personnes concernées. En tant que personne concernée, si ce machin là est sur une page web, je ne cherche pas un moyen d'arrêter le mouvement, je ferme la page (et c'est d'ailleurs ce qui s'est passé avec le lien que tu as donné 😅). Donc en vérité, pour les contenus animés, une règle réellement en faveur des personnes handicapées, devrait être "tout contenu en mouvement n'exécute pas de mouvement sans consentement préalable". En gros, au lieu d'avoir un moyen de mettre en pause, on va avoir un moyen de démarrer le mouvement si on le souhaite. Mais ici, sans mouvement, ce graphique n'a pas d'intérêt donc si le mouvement est trop rapide et peut causer des problèmes, alors il faut aussi pouvoir régler individuellement la vitesse. Mais il reste encore le problème d'accès pour les personnes aveugles…

Bref, ça fait beaucoup trop de solutions à trouver pour un si p'tit truc…

Et oui, **tout élément qui n'a pas de solution pour être accessible se doit de ne pas être utilisé**. Sinon, on discrimine et ce n'est pas acceptable de dire "bah désolée, on n'a pas de solution". C'est hyper violent. Et c'est bien ça qui est extrême.

Ici, on pourrait rendre compte de la progression avec un "simple" graphique en courbes statiques et on pourra avoir une alternative en version texte pour les personnes aveugles. Ce serait amplement suffisant pour l'information qu'on veut transmettre.

**Comment by florianMo** [comment]
ok je comprends, je suis rapidement tombé sur le point de "pas d'animation sans consentement" ce qui me semble très raisonnable. Peut être que l'info qui nous manquait est que je voulais juste lancer l'idée de ce genre de graphe, et non ce graphe/cette librairie en particulier (d'où mon "premier exemple trouvé", je ne sais même pas quelle lib est utilisée ici). Et donc si on voulait faire ça il faudrait trouver une implémentation respectant l'accessibilité, et je pense en effet que ce sera compliqué pour une faible valeur ajoutée.

Je poursuivrais bien cette discussion sur le fond mais c'est pas le lieu :).

**Comment by juliemoynat** [comment]
Je suis totalement partante pour une représentation non animée de l'évolution dans le classement car ce serait le plus simple à mettre en oeuvre et à rendre accessible. Je ne m'y connais pas trop en graph mais j'imagine qu'il doit y avoir un moyen sympa de le faire.

Pour poursuivre la discussion sur le fond, on peut effectivement le faire plutôt par ailleurs ;-)

**Comment by florianMo** [comment]
et quel serait ta reco comme plate-forme de diagnostic accessibilité en ligne ? Il y en a un paquet, il me semblait que la DINUM (à qui je serais prêt à faire confiance) en avait créé un mais je le retrouve pas.

**Comment by juliemoynat** [comment]
La DINUM a conçu un outil qui permet d'auditer un site web via un outil en ligne plutôt que via une grille de tableur. Ça s'appelle [ARA](https://ara.numerique.gouv.fr/). Mais c'est un outil destiné, comme les grilles de tableur, aux personnes qui connaissent suffisamment les règles d'accessibilité pour faire un audit.

Pour faire un audit, on s'appuie sur le [RGAA qui est un référentiel constitué de 106 critères](https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/) et, si tu prends un peu le temps de le lire, tu constateras assez vite que, sans formation sur le sujet, c'est assez difficile à utiliser/comprendre (certains critères, même en étant formé·es sont imbuvables… et c'est pas faute de l'avoir signalé). En gros, tous les critères demandant si tel ou tel truc est pertinent sont impossibles à traiter pour des personnes non formées.

Un audit se réalise manuellement. Très peu de critères (on estime à 20-30% maximum) sont testables automatiquement et quand ils le sont, en général, cela nécessite un contrôle manuel ensuite.

Il existe aussi des outils permettant donc de vérifier ces critères testables automatiquement, [tu en trouveras quelques uns ici](https://wiki.lalutineduweb.fr/accessibilite/tester/) mais, pareillement, c'est parfois difficile de comprendre ce qui est remonté et surtout de savoir comment corriger ce qui est remonté si on n'est pas formé·e.

Si tu veux commencer à creuser le sujet, j'ai regroupé [quelques guides d'apprentissage par ici](https://wiki.lalutineduweb.fr/accessibilite/guides-apprentissage/).

(Si tu as d'autres questions sur l'accessibilité, n'hésites pas à m'envoyer plutôt un mail via mon site web ; comme ça on restera plutôt sur le sujet du graph ici 😉)

**Comment by florianMo** [comment]
nickel merci !
