### ISSUE TITLE
Ajouter un status indiquant l'évolution dans le classement

### ISSUE THREAD

**Issue by D4llo** [cedricr/100joursdezbeul#70]
On peut utiliser une flèche ou autre.

![image](https://user-images.githubusercontent.com/131776117/235363789-43131098-f342-40d2-8af0-9b2f0cad9e04.png)

**Comment by cedricr** [comment]
Je vais mettre ça en place ce week-end je pense; @juliemoynat on passe par des svg comme pour le rang, pour éviter les pbs des emojis? Tu aurais qq chose dans tes cartons si jamais?

**Comment by juliemoynat** [comment]
@cedricr Tu veux quoi ? Une flèche vert le haut verte et une flèche vers le bas rouge ?

**Comment by cedricr** [comment]
@juliemoynat par exemple, sauf si tu as une meilleure idée! il faut peut-etre un indicateur "pas de changement aussi", et à voir si tout de suite ou plus tard, on introduit aussi un indicateur 'changement majeur' (genre +/- 10 places)? (ex: https://www.tiobe.com/tiobe-index/)

Après peut-etre que l'idée des fleches n'est pas la bonne, et qu'il faut mieux afficher juste un indicateur numérique ? Mais en plus du rang, du numero de département et des points ça peut faire beaucoup...

**Comment by juliemoynat** [comment]
@cedricr il y a déjà beaucoup de chiffres donc l'indicateur visuel me semble pas mal.

Pour le changement majeur, ça peut être double flèche vers le haut. Je vais tenter un truc.

**Comment by cedricr** [comment]
@juliemoynat je ne sais pas si c'est mieux de laisser vide ou de mettre un '=', oui il faut faire le test

**Comment by juliemoynat** [comment]
![flèches](https://user-images.githubusercontent.com/6296770/236633820-4f1bd844-e6c3-4662-99f5-14dda77b9eb4.png)

J'ai mis les flèches et signe égal sur une capture d'écran donc ça ne dit rien de leur emplacement mais c'est pour la mise en contexte. J'ai fait des flèches scotch 😁

**Comment by cedricr** [comment]
C'est génial :grinning:

**Comment by D4llo** [comment]
Proposition de ne mettre que les augmentations. Je ne sais pas si c'est très festif de pointer du doigt les descentes dans le classement.

Comme vous voulez

**Comment by juliemoynat** [comment]
De mon côté, je le voyais comme un encouragement à remonter dans le classement mais ça me va de ne mettre que les augmentations.

**Comment by cedricr** [comment]
ok pour moi aussi!

**Comment by SvenLochner** [comment]
Si je peux me permettre de rejoindre la discussion, je trouve l'idée très bonne aussi. Je pense que mettre que les progressions donne un côté très bon enfant. Je mets aussi deux versions basées sur le scotch (super idée ça @juliemoynat), je les trouve un peu plus minimalistes mais ça perds un peu le côté scotch (surtout pour la version A).

**Idée A**
![Fleche Up A](https://github.com/cedricr/100joursdezbeul/assets/91607339/5447ee49-67ee-4e46-8e8c-73f22c124892)

**Idée B**
![Fleche Up B](https://github.com/cedricr/100joursdezbeul/assets/91607339/8370d492-6470-478a-bae3-d284eef49779)

**Rendu**
![Zbeul Arrow](https://github.com/cedricr/100joursdezbeul/assets/91607339/798e4a5b-fa1c-40a0-b533-fdc5dc133f22)

**Comment by juliemoynat** [comment]
@SvenLochner J'ai un peu de mal à me prononcer ce soir car je suis fatiguée mais j'ai une question qui pourrait aider à se décider. Qu'est-ce que ça donne si on double la flèche pour indiquer la forte progression comme dans mon exemple au-dessus ? 🤔

**Comment by cedricr** [comment]
La première version sur https://github.com/cedricr/100joursdezbeul/issues/70#issuecomment-1537167993 me paraissait plus lisible.
