### ISSUE TITLE
Inclure les membres du Conseil Constitutionnel

### ISSUE THREAD

**Issue by D4llo** [cedricr/100joursdezbeul#74]
Hello,

Voici la liste des 9 membres du Conseil Constitutionnel :

- Laurent Fabius
- Michel Pinault
- Corinne Luquiens 
- Jacques Mézard 
- François Pillet
- Alain Juppé 
- Jacqueline Gourault 
- François Seners
- Véronique Malbec

Je ne sais pas qui a soutenu ou non le projet. Est-ce qu'on ne les mettra pas tous les 9 ? Je vous laisse en discuter ici.

À discuter dans la continuité de #69, #71 et cela aura aussi un lien avec #73

**Comment by juliemoynat** [comment]
[La décision du Conseil constitutionnel est disponible sur leur site](https://www.conseil-constitutionnel.fr/decision/2023/2023849DC.htm).

À la fin, on peut y lire ceci :

> Jugé par le Conseil constitutionnel dans sa séance du 14 avril 2023, où siégeaient : M. Laurent FABIUS, Président, Mme Jacqueline GOURAULT, M. Alain JUPPÉ, Mmes Corinne LUQUIENS, Véronique MALBEC, MM. Jacques MÉZARD, François PILLET, Michel PINAULT et François SÉNERS.

Par conséquent, je pense qu'on peut toustes les compter. On dirait que la décision du CC est au consensus à priori.

J'approuve l'idée de les compter comme personnalités cibles.

**Comment by cedricr** [comment]
Je ferme en bloc toutes les issues de nouvelles personnalités/nouvelles actions. On y repensera éventuellement plus tard.
