### ISSUE TITLE
Inclure une reconnaissance des actions libres

### ISSUE THREAD

**Issue by D4llo** [cedricr/100joursdezbeul#75]
J'aimerai aussi ajouter une target vide/libre. L'idée est valoriser à juste titre une belle action de zbeul si et seulement si elle est dans le contexte de la réforme des retraires. Ce contexte peut se prouver avec une photo de banderole ou un chant ou autre.

Ajouter cette possibilité est particulièrement efficace pour entendre les appels des lieux honteusement boudés par le gouvernement !

```ts
export const TARGET_MULTIPLIER = {
	'libre': 0.5,
	'secretaire-etat': 1,
	'ministre-del': 2,
	'ministre': 3,
	'ministre-int': 4,
	'presidente-an': 4,
	'premiere-min': 5,
	'president-rep': 6
};
```

Cela nous permet de soutenir ce genre d'action: [Réforme des retraites. 500 personnes défilent au son des casseroles à Nantes](https://www.ouest-france.fr/economie/retraites/500-personnes-defilent-au-son-des-casseroles-a-nantes-a9e7cb0c-e2c9-11ed-b514-8dd13d8be671).

Issue extraite de #3

**Comment by juliemoynat** [comment]
Je suis d'accord avec ça surtout que la prochaine journée intersyndicale est dans un mois donc il faut encourager à tenir le mouvement.

J'aimerais y voir un coefficient multiplicateur selon le nombre de personnes présentes à l'action libre. On peut faire des paliers par centaine, par exemple. À partir de 100, on gagne un peu plus de points et puis on augmente à chaque centaine ?

**Comment by juliemoynat** [comment]
Ah oui, bien vu. Ok pour ignorer la quantité alors !

**Comment by fambon** [comment]
exemple d'action freelance imaginative :
https://contre-attaque.net/2023/05/05/lyon-les-locaux-du-medef-mures-dans-la-nuit/

ça vaut des points ! c'est pas listé chez Attac et c'est sans casseroles, mais c'est non-violent et dans le sens du vent.

**Comment by D4llo** [comment]
Je vois pas de tag sur le sujet des retraites. A voir si on veut valoriser ou non

**Comment by fambon** [comment]
bah, ça semble juste viser le medef (qui s'en dedit piteusement cf l'article du Progrès) 
Le texte donne le "tag" retraites :

> Le lobby patronal est l’un des derniers groupuscules qui soutient encore le gouvernement et lui réclame toujours plus de casse sociale. Le patronat organise la précarité, la destruction des allocations chômage ou le recul des retraites [...]

Et ça cite une casserolade du 27 avril qui visait le medef ; j'ai pas vérifié si le 69 a été crédité pour cette casserolade là :-)

**Comment by D4llo** [comment]
Si jamais on part sur un facteur pouvant donner des décimaux, je suis pour arrondir à l'entier suivant -> `ceil(0.5*1) == 1`

**Comment by cedricr** [comment]
On n'a pas les ressources coté données là-dessus, et ça va donner des arbitrages permanents => pas pour le moment!
