### ISSUE TITLE
Ajouter également un classement régional

### ISSUE THREAD

**Issue by D4llo** [cedricr/100joursdezbeul#76]
Ce serait cool de faire également un classement régional car pas mal de gens se déplace sur leur région pour mener les actions !
Cela implique de grouper les datas en région.

![image](https://user-images.githubusercontent.com/131776117/235369243-9d9b45eb-7e38-48a7-99cb-ce7b39f8a1c9.png)

Toutes les infos sont sur Wikipédia : https://fr.wikipedia.org/wiki/R%C3%A9gion_fran%C3%A7aise

Qui se motive pour s'en occuper ?

**Comment by cedricr** [comment]
On a déjà le code region dans le departement.json

**Comment by cedricr** [comment]
et dès que j'ai un moment j'y rajouterai les populations, qui finiront bien par nous servir
