### ISSUE TITLE
Ajouter un système de palier national pour faire progresser la France sur le chemin de l'apaisement

### ISSUE THREAD

**Issue by D4llo** [cedricr/100joursdezbeul#80]
hello,

Pour savoir si nous avançons dans la bonne direction, l'idée serait de quantifier le niveau d'apaisement national. Ce niveau serait une jauge à la façon d'un thermomètre. Tous les N pts nationaux (genre 1000) on passe au palier suivant.

1. Tranquille
2. Détendu
3. Reposé
4. Méditatif
5. Ataraxique

À voir

**Comment by hguemar** [comment]
J'apprécie l'idée et l'hommage involontaire à ma personne :rofl: :+1:

**Comment by greenboy59** [comment]
Très bonne idée +1

**Comment by D4llo** [comment]
@greenboy59 motivé pour te lancer sur ce développement ?
