### ISSUE TITLE
Ajouter un bonus action reactive pour les actions organisées en 24h

### ISSUE THREAD

**Issue by D4llo** [cedricr/100joursdezbeul#86]
Bonjour,

La secrétaire d’État à la Jeunesse, Sarah El Haïry (#73) vient de réaliser une visite surprise à Nantes.

Surprise car la visite n'a pas été connu par Attac [On ne les lâche pas ! La carte des mobilisations](https://france.attac.org/se-mobiliser/retraites-pour-le-droit-a-une-retraite-digne-et-heureuse/article/on-ne-les-lache-pas-la-carte-des-mobilisations) et que l'agenda de Sarah El Haïry ne l'a pas mentionnée [Agenda de la Secrétaire d'État](https://www.jeunes.gouv.fr/agenda-de-la-secretaire-d-etat-115)

L'action a fuité la veille dans le journal Le Télégramme [Sarah El Haïry : « Pas de service national universel obligatoire à la rentrée 2023 »](https://www.letelegramme.fr/france/sarah-el-hairy-pas-de-service-national-universel-obligatoire-a-la-rentree-2023-04-05-2023-13330883.php)

Ce qui permis à un groupe d'organiser rapidement un accueil sur le pouce : [Des manifestants organisent une casserolade à Vertou pour la venue de Sarah El Haïry](https://www.ouest-france.fr/pays-de-la-loire/vertou-44120/des-manifestants-organisent-une-casserolade-a-vertou-pour-la-venue-de-sarah-el-hairy-98d71c78-eb57-11ed-ac96-1441ecffeb34)

Cette partie de cache-cache dans la sympathique commune de Vertou, mérite je pense qu'on se questionne sur ce laps de temps très court et sur notre volonté de récompenser cette réactivité qui sera de plus en plus nécessaire durant tout l'apaisement.

![image](https://user-images.githubusercontent.com/131776117/236528932-1ff1e258-03e0-476b-ae6d-cbf626339cda.png)

**Comment by juliemoynat** [comment]
J'aime bien l'idée mais est-ce qu'avoir une preuve formelle de ça n'est pas difficile ? On peut le déduire par une succession d'évènements mais c'est un peu de la devinette, je pense (bon nous, on le sait pour cet évènement parce qu'on a eu des infos en interne syndicat mais il n'y a pas d'écrit public formel).

**Comment by D4llo** [comment]
ok Je pense en wontfix pour le moment. On verra plus tard si c'est redemandé
