### ISSUE TITLE
Pondérer le calcul des points en fonction de la population des départements

### ISSUE THREAD

**Issue by cedricr** [cedricr/100joursdezbeul#87]
- [ ] récupérer la infos de population, et les ajouter au fichier [departements.json](https://github.com/cedricr/100joursdezbeul/blob/main/src/lib/assets/departements.json)
- [ ] calculer les points pondérés (le chiffre actuel reste le minimum, et on pourrait le multiplier par popParis/popDept)

**Comment by florianMo** [comment]
Je me lancerais bien là dessus :)
